### ISSUE TITLE
FizzBuzz 問題

### ISSUE THREAD

**Issue by macha3162** [macha3162/homework#1]
FizzBuzz 問題を解くプログラムを作成してください。

ルールは以下の通り

```
1から順番に数を表示する
その数が3で割り切れるなら”Fizz”、5で割り切れるなら”Buzz”、両方で割り切れるなら”FizzBuzz”と表示する
要するに”1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz ･･･”と出力される
```

検索すると答えも出てきますが、大人の対応でお願いします。

課題提出は 03_fizz_buzz.rb でリポジトリに登録してください。

**Comment by macha3162** [comment]
push 時のメッセージは以下のフォーマットで書いてください。
pushがIssueと関連づきます。

`issue #1 FizzBuzz問題提出`

**Comment by macha3162** [comment]
提出ありがとうございます。
↑PushとIssueが紐付いたのがわかったと思います。
bba0ea7 ここから、今回変更された内容が分かるんですよ〜

FizzBuzzが解けたら、また同じようにPushしてください。

**Comment by macha3162** [comment]
残念ながら、1が出ていないようです。
仕様を満たしていないと、バグとして扱われてしまいます。
修正してください。

終わったらIssueを幾つか用意しているので、
好きなモノをアサインして課題に取り組んでみてください。
もちろん読書の合間で結構です。

**Comment by ghost** [comment]
修正しました。

新しい課題ありがとうございます。
取り組んでみます。

**Comment by macha3162** [comment]
確認しました。　OKです。　Closeしますね。
