### ISSUE TITLE
マカオのオカマ問題

### ISSUE THREAD

**Issue by macha3162** [macha3162/homework#3]
入力されたテキストが回文であるか判定するプログラムを作成してください。
回文とは以下のように前から読んでも後ろから読んでも同じである文のことです。

eye
level
しんぶんし
たけやぶやけた
マカオのオカマ
プログラムが完成したら、次の顔文字が回文になるか判定してみてください。

＾－＾
(｡-﹏-｡)
(＾〇＾)
全てが回文になるわけではないですね・・
このような顔文字も回文として判定できると嬉しいですね (＾〇＾)

**Comment by ghost** [comment]
顔文字の記号判定用のメソッドを入れてみたのですが、
全角の括弧("（"など)やスラッシュ、(´・ω・`)←の眉毛部分がうまく判定できず断念しました。。

**Comment by macha3162** [comment]
いえいえ十分でございます。　合格。
対応有難うございました。

ちなみにこんな書き方も出ます。

```
text = 'よるにんじんにるよ'; text == text.reverse ? '回文です' : '回文ではありません'
```
