### ISSUE TITLE
ページタイトル取得

### ISSUE THREAD

**Issue by macha3162** [macha3162/homework#4]
WebPageのページタイトルを取得するプログラムを作ってください。

例:
$> ruby get_title.rb https://www.synergy-marketing.co.jp/blog/
CRMやWebマーケティングに関する解説やノウハウを発信｜シナジーマーケティングBLOG

**Comment by macha3162** [comment]
ヒント：require 'open-uri' を使うと、Webpgeをまるでローカルのファイルのように扱えますよ。

**Comment by ghost** [comment]
やります

**Comment by macha3162** [comment]
お願いします。

**Comment by ghost** [comment]
いろいろなWebPageで試したところ、おおよそはタイトルを取得できましたが、
シナジーマーケティングBLOGからは取得できずに手詰まりました。。

**Comment by macha3162** [comment]
お疲れ様でした。　例に出したページがちょっと意地悪でしたね。
でも、ある程度で見切りをつけるのも大切です。

修正版をUPしましたので、差分を確認して、
他のブログ、シナジーのブログとの違いを考えてみてください。

**Comment by macha3162** [comment]
差分は上記のリンクから見れます。
なんとなく答えがわかったら、このチケットをCloseしておいてください。

**Comment by ghost** [comment]
修正版を拝見しました。
他のブログは空白文字や改行のないものが多かったので、それが違いかな？と考えています。
改行のことは考えて書いてみたのですが扱い方を間違えていました。
勉強になります。有難うございます。
