### ISSUE TITLE
ループ処理

### ISSUE THREAD

**Issue by macha3162** [macha3162/homework#5]
今、任意の個数のメールアドレスがあり、ドメイン別にメールアドレスが何個あるかを調べたい。
メールアドレスの配列 ary を引数として取り、ハッシュオブジェクトを返すメソッド foo を作りなさい。
ただし、そのハッシュオブジェクトは以下の条件を満たすこと。

各キーはメールアドレスのドメイン部分(@より後ろの部分)である。
各値は、そのドメイン部分がキーと合致するメールアドレスの個数である。
例えば、次のようなメールアドレスの集合を考える。

``` john@sample.com
taro@sample.jp
nancy@sample.com
jiro@sample.jp
hermes@synm.jp
saburo@sample.jp
```

```
'sample.com' => 2,
'sample.jp' => 3,
'synm.jp' => 1
```

なお、ary に含まれるメールアドレスは、途中にアットマーク(@)を1個だけ含む文字列で、ドメイン部分は英小文字、数字、ドット(.)により構成されているものとする。また、ary に重複したメールアドレスは含まれていないものとする。

**Comment by macha3162** [comment]
ヒント：Hashと配列のSplitの組み合わせですね。

**Comment by yoshio8927** [comment]
'sample.com' => 2,
'sample.jp' => 3,
'synm.jp' => 1

この部分は実行結果ですか？。

**Comment by macha3162** [comment]
はい。　実行結果です。
忠実に真似なくてもOKです。

例えば、CSV形式にするとかでもOK

**Comment by macha3162** [comment]
コミットログは 「issues #5 課題」このようにチケット番号を離して記入してくださいね。
b1aa5e66bcbb916ce5fa8903ddb1ebf107a6ab70
チケットと関連付けされず、気づくのが遅れてしまいます。

改善点はいくつかありますが、出来てますね！
改善点を修正してコミットしてください。

**Comment by macha3162** [comment]
合格！
