### ISSUE TITLE
お天気問題

### ISSUE THREAD

**Issue by macha3162** [macha3162/homework#8]
WEB API を利用して本日の大阪の天気を表示させましょう。
Livedoor Weather API が登録が必要なく利用できるので簡単です。

http://weather.livedoor.com/weather_hacks/webservice
![weather](https://cloud.githubusercontent.com/assets/359262/6475118/5bba73b0-c24a-11e4-97c8-2b1780a57a32.png)

**Comment by macha3162** [comment]
ヒント：require 'open-uri' を使うと、Webpgeをまるでローカルのファイルのように扱えますよ。

**Comment by macha3162** [comment]
第2ヒント: require 'json'

**Comment by ghost** [comment]
やります

**Comment by macha3162** [comment]
すごい!
メキメキ力をつけてますね。　これも立派なクローリングスクリプト。

```
curl -L https://raw.githubusercontent.com/macha3162/homework/448e796e3f4af2541959b15a003905d2ab2d0716/okt73/get_weather.rb | ruby
```
